### ISSUE TITLE
new key events creator throws out error (for now commented that part of code)

### ISSUE THREAD

**Issue by perkel666** [perkel666/Savy-life#8]
main.py
s: 122
e: 153

Error log:

Traceback (most recent call last):
  File "D:/Coding/Projects/Git Projects/Savy-life/main.py", line 207, in <module>
    game.main_loop()
  File "D:/Coding/Projects/Git Projects/Savy-life/main.py", line 91, in main_loop
    self.get_input()
  File "D:/Coding/Projects/Git Projects/Savy-life/main.py", line 124, in get_input
    if event.type == pygame.MOUSEBUTTONDOWN and event.key == 1:
AttributeError: event member not defined

**Comment by perkel666** [comment]
- fixed
